version: '3'

services:
  import:
    image: ghcr.io/bih-cei/mesh-terms-de-import:main
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mesh
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWD=meshterms

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=mesh
      - POSTGRES_PASSWORD=meshterms
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-data:
